import { db, auth } from 'hatchable';
import { getAppAccess } from '../lib/access.js';
export const access='user'; export const methods=['GET'];
export default async function(req,res){
 const user=await auth.getUser(req);
 const appAccess=await getAppAccess(req);
 if(!appAccess)return res.status(403).json({error:'You do not have MSA Academy access. Ask the owner to grant access to your email.'});
 const manager=['owner','manager'].includes(appAccess.access_type);
 const p=await db.query("SELECT p.id,p.name,p.sport,p.level,p.date_of_birth,p.passport_cpr,p.guardian_contact,p.address,p.gender,p.nationality,COALESCE(p.tennis_categories,'{}') AS tennis_categories,COALESCE(json_agg(DISTINCT jsonb_build_object('id',pr.id,'registration_no',pr.registration_no,'registration_type',pr.registration_type,'sport',COALESCE(pr.sport,pk2.sport),'tennis_categories',COALESCE(pr.tennis_categories,'{}'),'package_id',pr.package_id,'package_name',pk2.name,'package_type',pk2.package_type,'sessions_per_week',pr.sessions_per_week,'duration_weeks',pr.duration_weeks,'start_date',pr.start_date,'number_weeks',pr.number_weeks,'reference_price',pr.reference_price,'net_price',pr.net_price,'discount_percentage',pr.discount_percentage,'discounted_price',pr.discounted_price,'created_at',pr.created_at,'registration_date',pr.registration_date,'paid',pr.paid,'ar',NOT pr.paid,'session_ids',COALESCE((SELECT json_agg(prs.session_id) FROM player_registration_slots prs WHERE prs.registration_id=pr.id),'[]'))) FILTER (WHERE pr.id IS NOT NULL),'[]') AS registrations,COALESCE(json_agg(DISTINCT jsonb_build_object('id',pk.id,'name',pk.name,'sport',pk.sport)) FILTER (WHERE pk.id IS NOT NULL),'[]') AS packages FROM players p LEFT JOIN player_registrations pr ON pr.player_id=p.id LEFT JOIN packages pk2 ON pk2.id=pr.package_id LEFT JOIN player_packages pp ON pp.player_id=p.id LEFT JOIN packages pk ON pk.id=pp.package_id WHERE p.active=true GROUP BY p.id ORDER BY p.name");
 const c=await db.query("SELECT id,name,sport,COALESCE(sports,ARRAY[sport]) AS sports FROM coaches WHERE active=true ORDER BY name");
 const pk=await db.query('SELECT id,name,sport,sessions_per_week,duration_weeks,price,net_price,package_type,start_date,end_date,active FROM packages WHERE active=true ORDER BY name');
 const s=await db.query("SELECT s.id,s.sport,s.day_of_week,s.start_time,s.coach_id,s.start_date,s.end_date,s.location,COALESCE(s.tennis_categories,'{}') AS categories,COALESCE(string_agg(DISTINCT c2.name, ' / ' ORDER BY c2.name) FILTER (WHERE c2.id IS NOT NULL),c.name) AS coach_name,COALESCE(array_agg(DISTINCT c2.id) FILTER (WHERE c2.id IS NOT NULL),CASE WHEN c.id IS NOT NULL THEN ARRAY[c.id] ELSE '{}' END) AS coach_ids,COALESCE(json_agg(json_build_object('id',p.id,'name',p.name,'status','Pending') ORDER BY p.name) FILTER (WHERE p.id IS NOT NULL),'[]') AS players FROM academy_sessions s LEFT JOIN coaches c ON c.id=s.coach_id LEFT JOIN session_coaches sc ON sc.session_id=s.id LEFT JOIN coaches c2 ON c2.id=sc.coach_id LEFT JOIN session_players sp ON sp.session_id=s.id LEFT JOIN players p ON p.id=sp.player_id GROUP BY s.id,c.id,c.name ORDER BY s.day_of_week,s.start_time");
 const occ=await db.query("SELECT o.id,o.player_id,o.session_id,o.session_date,o.status,o.registration_id,p.name AS player_name FROM player_schedule_occurrences o JOIN players p ON p.id=o.player_id ORDER BY o.session_date,o.session_id,p.name");
 const guests=await db.query("SELECT id,academy_session_id,guest_name,status,session_date FROM attendance_guests ORDER BY session_date,academy_session_id,guest_name");
 const evaluations=await db.query("SELECT e.id,e.player_id,e.sport,e.evaluation_date,e.coach_id,c.name AS coach_name,e.overall_rating,e.level,e.scores,e.strengths,e.focus_areas,e.comments,e.created_at,e.updated_at FROM player_evaluations e LEFT JOIN coaches c ON c.id=e.coach_id ORDER BY e.evaluation_date DESC,e.created_at DESC");
 const players=manager?p.rows:p.rows.map(x=>({id:x.id,name:x.name,sport:x.sport,level:x.level,tennis_categories:x.tennis_categories,registrations:x.registrations||[],packages:[]}));
 res.json({players,coaches:manager?c.rows:[],packages:manager?pk.rows:[],sessions:s.rows,occurrences:occ.rows,guests:guests.rows,evaluations:evaluations.rows,user:{...user,app_access:appAccess.access_type}});
}